### ISSUE TITLE
remove monogdb completly 

### ISSUE THREAD

**Issue by PhilipDominik** [SergPerep/tasklist#2]
is it possible to remove mongodb completly and have everything on one database? 
If yes what do I need to change/remove in the project?

Best regards

Hantid

**Comment by SergPerep** [comment]
Hi @PhilipDominik,

Yes it is possible. I even consider it myself.

In MongoDB I implement sessions with [express-session](https://github.com/expressjs/session). At the end of [readme file of express-session repository](https://github.com/expressjs/session) you can find a list of modules that you can use to configure connection to various databases. The list is pretty comprehensive.

I use [express-session](https://github.com/expressjs/session) + [connect-mongo](https://www.npmjs.com/package/connect-mongo) for MongoDB. If you want to store sessions in postgreSQL instead, you will need [express-session](https://github.com/expressjs/session) + [connect-pg-simple](https://www.npmjs.com/package/connect-pg-simple). After you make your choice and install modules, go to [index.js](https://github.com/SergPerep/tasklist/blob/master/index.js) to configure database-connection for sessions.

Can't promise that it will work right away: maybe you will need to tweak other stuff a little bit, but in a nutshell this is it.
